kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - ../../base
nameSuffix: -dev
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: dotnet-ms-ingress
    path: ingress.yaml
images:
  - name: ghcr.io/botopsy/dotnet-ms
    newTag: fe6df9c
